version: "3.8"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "botdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - botdb-temp:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]

volumes:
  botdb-temp:
    driver: local